import { useEffect } from "react";

const CONTENT = {
  terms: {
    title: "Terms of Service",
    updated: "April 2026",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: "By accessing or using WanderViet, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform."
      },
      {
        heading: "2. Account Registration",
        body: "You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years old to register."
      },
      {
        heading: "3. Use of the Platform",
        body: "WanderViet grants you a limited, non-exclusive, non-transferable license to access and use the platform for personal, non-commercial purposes. You agree not to: misuse our services, attempt to gain unauthorized access, post false or misleading content, or violate any applicable laws."
      },
      {
        heading: "4. Bookings and Payments",
        body: "When you make a booking through WanderViet, you enter into a direct agreement with the service provider. WanderViet acts as an intermediary and is not responsible for the quality of services provided by third-party businesses. All prices are inclusive of applicable taxes unless stated otherwise."
      },
      {
        heading: "5. Cancellation Policy",
        body: "Cancellation policies vary by location and service provider. Please review the specific cancellation terms before completing a booking. WanderViet reserves the right to process refunds in accordance with the agreed policy at the time of booking."
      },
      {
        heading: "6. User Content",
        body: "By submitting reviews, photos, or other content, you grant WanderViet a non-exclusive, royalty-free license to use, display, and distribute that content. You represent that you own or have the necessary rights to the content you submit."
      },
      {
        heading: "7. Limitation of Liability",
        body: "WanderViet is not liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid for the specific service giving rise to the claim."
      },
      {
        heading: "8. Changes to Terms",
        body: "We may update these Terms from time to time. Continued use of WanderViet after changes constitutes acceptance of the updated terms. We will notify users of significant changes via email or in-app notification."
      },
      {
        heading: "9. Governing Law",
        body: "These Terms are governed by the laws of the Socialist Republic of Vietnam. Any disputes shall be resolved through the courts of Vietnam."
      },
      {
        heading: "10. Contact",
        body: "For questions about these Terms, please contact us at legal@wanderviet.vn or write to: WanderViet, Hanoi, Vietnam."
      },
    ]
  },

  privacy: {
    title: "Privacy Policy",
    updated: "April 2026",
    sections: [
      {
        heading: "1. Information We Collect",
        body: "We collect information you provide directly (name, email, phone, travel preferences), information generated by your use of the platform (bookings, reviews, browsing history), and technical data (device type, IP address, cookies)."
      },
      {
        heading: "2. How We Use Your Information",
        body: "We use your information to: provide and improve our services, personalize your travel recommendations, process bookings and payments, send service-related communications, and comply with legal obligations."
      },
      {
        heading: "3. Travel Preferences & Personalization",
        body: "The interests you select during registration (e.g. Beach, Culture, Adventure) are used solely to personalize your experience on WanderViet. This data is never sold to third parties and you can update or remove it at any time from your profile settings."
      },
      {
        heading: "4. Information Sharing",
        body: "We share your information only with: service providers you book with (name, contact for booking purposes), trusted third-party services that help us operate the platform, and authorities when required by law. We do not sell your personal data."
      },
      {
        heading: "5. Data Security",
        body: "We implement industry-standard security measures including encryption, secure servers, and regular security audits. However, no method of transmission over the internet is 100% secure. We encourage you to use a strong, unique password."
      },
      {
        heading: "6. Cookies",
        body: "We use cookies and similar technologies to maintain your session, remember your preferences, and analyze platform usage. You can control cookie settings in your browser, though some features may not function properly without them."
      },
      {
        heading: "7. Your Rights",
        body: "You have the right to: access, correct, or delete your personal data; withdraw consent at any time; opt out of marketing communications; request data portability. To exercise these rights, contact us at privacy@wanderviet.vn."
      },
      {
        heading: "8. Data Retention",
        body: "We retain your data for as long as your account is active or as needed to provide services. You may request deletion of your account and associated data at any time, subject to retention requirements under applicable law."
      },
      {
        heading: "9. Children's Privacy",
        body: "WanderViet is not intended for children under 18. We do not knowingly collect personal information from minors. If we become aware that a minor has provided us with personal data, we will delete it promptly."
      },
      {
        heading: "10. Contact",
        body: "For privacy-related questions or requests, contact our Data Protection team at privacy@wanderviet.vn."
      },
    ]
  }
};

export default function LegalModal({ type, onClose }) {
  const content = CONTENT[type];

  // Close on Escape
  useEffect(() => {
    const handler = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", handler);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", handler);
      document.body.style.overflow = "";
    };
  }, [onClose]);

  if (!content) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center
                    p-0 sm:p-4 bg-black/60 backdrop-blur-sm"
         onClick={onClose}>
      <div
        className="bg-white dark:bg-slate-900 w-full sm:max-w-xl rounded-t-3xl sm:rounded-2xl
                   border dark:border-slate-700 shadow-2xl flex flex-col max-h-[90vh]"
        onClick={e => e.stopPropagation()}>

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b
                        border-gray-100 dark:border-slate-800 shrink-0">
          <div>
            <h2 className="font-bold text-gray-900 dark:text-white text-lg">
              {content.title}
            </h2>
            <p className="text-xs text-gray-400 dark:text-slate-500 mt-0.5">
              Last updated: {content.updated}
            </p>
          </div>
          <button onClick={onClose}
            className="w-8 h-8 rounded-full flex items-center justify-center
                       text-gray-400 hover:text-gray-700 dark:hover:text-white
                       hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors text-xl">
            ×
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5">
          {content.sections.map((s, i) => (
            <div key={i}>
              <h3 className="font-semibold text-gray-900 dark:text-white text-sm mb-1.5">
                {s.heading}
              </h3>
              <p className="text-sm text-gray-600 dark:text-slate-400 leading-relaxed">
                {s.body}
              </p>
            </div>
          ))}

          <div className="border-t border-gray-100 dark:border-slate-800 pt-4">
            <p className="text-xs text-gray-400 dark:text-slate-500 text-center">
              WanderViet · legal@wanderviet.vn
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-100 dark:border-slate-800 shrink-0">
          <button onClick={onClose}
            className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white
                       font-semibold rounded-xl text-sm transition-colors">
            I understand
          </button>
        </div>
      </div>
    </div>
  );
}